---
name: Checkov IaC Scanning
on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'staging/ap-southasia-1/staging/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true
          framework: terraform
          container_user: 1000
          output_format: github_failed_only
          soft_fail: false
          
      - name: add-plan-comment
        id: comment
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && (success() || failure())
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            #### Checkov 🧪\`${{ steps.checkov.outcome }}\`
      
            <details><summary>Show Checkov Results</summary>

            ${process.env.CHECKOV_RESULTS}

            </details>
            
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
