---
name: Checkov IaC Scanning
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: staging/ap-southasia-1/staging
          framework: terraform 
          
      - name: Run Checkov and capture output
        id: checkov
        run: |
          echo "running checkov on directory: staging/ap-southasia-1/staging"
          checkov -d staging/ap-southasia-1/staging --output sarif --framework terraform
          echo "::set-output name=checkov-output::$(cat results.sarif)"

      - name: Comment on pull request
        uses: actions/github-script@v4
        with:
          script: |
            const output = `Checkov scan results:\n\n${process.env.checkov_output}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });