name: 'Checkov IaC Scanning'

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'staging/ap-southasia-1/staging/*'


jobs:
  checkov:
    name: 'checkov'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Run Checkov against configuration
    - name: Checkov
      if: github.event_name == 'pull_request'
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        quiet: true
        framework: terraform
        container_user: 1000
        output_format: github_failed_only
        soft_fail: false
    
    # Add a comment to pull requests with plan results
    - name: Run GitHub Script
      uses: actions/github-script@v6
      with:
        script: |
          const output = #### Checkov 🧪\`${{ steps.checkov.outcome }}\`

          <details><summary>Show Checkov Results</summary>

          ${process.env.CHECKOV_RESULTS}

          </details>
                      
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
